export enum InfraPSPErrorCode {
  // transaction related errors
  TRX_REF_TARGET_ACCOUNT_UNAVAILABLE = 'TRX_REF_TARGET_ACCOUNT_UNAVAILABLE',
  TRX_REF_MED_ONGOING = 'TRX_REF_MED_ONGOING',
  TRX_CREDIT_CARD_NOT_PROCESSED = 'TRX_CREDIT_CARD_NOT_PROCESSED',
  TRX_CREDIT_CARD_CONTACT_ISSUER = 'TRX_CREDIT_CARD_CONTACT_ISSUER',
  TRX_CREDIT_CARD_CONTACT_TENANT = 'TRX_CREDIT_CARD_CONTACT_TENANT',
  TRX_CREDIT_CARD_RESTRICTED = 'TRX_CREDIT_CARD_RESTRICTED',
  TRX_CREDIT_CARD_FRAUD_RISK = 'TRX_CREDIT_CARD_FRAUD_RISK',
  TRX_CREDIT_CARD_BLOCKED = 'TRX_CREDIT_CARD_BLOCKED',
  TRX_CREDIT_CARD_VERIFY_DATA = 'TRX_CREDIT_CARD_VERIFY_DATA',
  TRX_ANTIFRAUD_PROVIDER_ERROR = 'TRX_ANTIFRAUD_PROVIDER_ERROR',
  TRX_ANTIFRAUD_NOT_AUTHORIZED = 'TRX_ANTIFRAUD_NOT_AUTHORIZED',
  TRX_CREDIT_CARD_TOKENIZATION_ERROR = 'TRX_CREDIT_CARD_TOKENIZATION_ERROR',
  // antifraud related errors

  // transfer related errors
  TRF_PIX_KEY_NOT_FOUND = 'TRF_PIX_KEY_NOT_FOUND',

  // default
  UNKNOWN = '',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
